### ISSUE TITLE
客户端和服务端都多实例部署的情况下，有概率出现部分客户端实例获取不到最新配置

### ISSUE THREAD

**Issue by shayne-york** [philchia/agollo#111]
客户端建立长连接随机到其中一个服务端实例上，服务端会每隔1s去轮询是否有新配置，如果有就返回200。客户端收到通知后发起另外一个连接去获取配置，连接随机到其中一个服务端实例，如果这时该实例因为**缓存**恰好未同步到最新配置，就会返回老配置。

**Comment by shayne-york** [comment]
@philchia 您好，有什么方式更快更方便跟您联系吗

**Comment by philchia** [comment]
fixed by #116
