### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by yezl77** [philchia/agollo#13]
纠正一个小错误 namespace 多个地方拼成了 namepsapce

**Comment by philchia** [comment]
没看到有namepsapce，可以提个pr

**Comment by m20082008m** [comment]
// GetStringValueWithNameSapce get value from given namespace
func GetStringValueWithNameSapce(namespace, key, defaultValue string) string {
	return defaultClient.GetStringValueWithNameSapce(namespace, key, defaultValue)
}
这个好像还没改。。。
