### ISSUE TITLE
client.Start() will take some minutes to start when the namespaces not exist on Apollo

### ISSUE THREAD

**Issue by leikao** [philchia/agollo#14]
`client.Start()` will take some minutes to start when the namespace not exists on Apollo.

The reason is very simple, `Start()` method will invoke the `client.preload()` to long polling configuration data, the polling will hang for 1 minute by Apollo server if the namespace is missing.

Is there any way to speed up the `client.Start()` logic (except add the missing namespace on Apollo)?

My options:
1. For optional namespace, it's no need to pre-load when start;
2. For mandatory namespace, it must be fond from Apollo server or local cache.
So users could tag the namespace mandatory or optional when invoking `client.Start()`, `client.preload()` could invoke Apollo's `configs` API instead of `notifications/v2`, the `configs` API will return failure quickly when access missing optional namespaces, it will speed up the start process.

**Comment by philchia** [comment]
client.Start() will not block when namespace absent

**Comment by philchia** [comment]
what is your apollo server version?

**Comment by leikao** [comment]
> what is your apollo server version?

v0.11.0 @philchia

**Comment by leikao** [comment]
Apollo will hold the request up to 60 seconds according to [this wiki page](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97#142-http%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)

**Comment by philchia** [comment]
The initial request to this url will pass -1 as notificationId, so this request never blocks

**Comment by leikao** [comment]
It will block for at least 60 seconds if the namespace is absent, you can try it:

```go
package main

import (
    "time"
    "fmt"
    "net/url"
    "net/http"
)

const (
    ApolloServerEndpoint = "http://x.x.x.x:8080"   // Apollo Config Server Endpoint
    HttpClientTimeout = time.Second * 90    // Notification will timeout if < 60s when namespace absent.
)

func main() {
    testAgollo("xxx", "default", "switch")
    testAgollo("xxx", "default", "not-exists")
    testAgollo("xxx", "default", "switch")
}

func testAgollo(app, cluster, ns string) {
    t := time.Now()
    defer func() {
        fmt.Printf(">>>\tTime cost for namespace (%s): %v\n", ns, time.Since(t))
    }()

    u, _ := url.Parse(ApolloServerEndpoint)
    u, _ = u.Parse("/notifications/v2")

    req, _ := http.NewRequest(http.MethodGet, u.String(), nil)
    args := req.URL.Query()
    args.Add("appId", app)
    args.Add("cluster", cluster)
    args.Add("notifications", fmt.Sprintf("[{\"namespaceName\": \"%s\", \"notificationId\":-1}]", ns))
    req.URL.RawQuery = args.Encode()

    c := http.Client{Timeout: HttpClientTimeout}
    rsp, e := c.Do(req)
    if e != nil {
        fmt.Println("failed to send request to apollo: ", e)
        return
    }
    fmt.Println("apollo response code: ", rsp.StatusCode)
    return
}
```

**Comment by philchia** [comment]
You need to query all namesapce in one request, as the application namespace is the defaut namespace, so this request will return ASAP without block
