### ISSUE TITLE
关于app.properties中的ip一丁点疑问

### ISSUE THREAD

**Issue by zplzpl** [philchia/agollo#15]
其实ip应该是config server ，单纯叫ip，好像与配置所代表的业务没关联。

总觉得怪怪得。

**Comment by zplzpl** [comment]
不过相对来说，这个package设计的比较干净

**Comment by zplzpl** [comment]
@philchia 有个其它的问题想在这里也问一下，你们会有对象数组配置的场景吗？

类似下面这种情况：
是一个动态对象数组

```
[[person]]
id=1
name="a"
[[person]]
id=2
name="b"
```

这种在apollo中，支持吗？或者是你们遇到，你们是怎么解决这种场景？thanks

**Comment by philchia** [comment]
这个直接放在一个yaml的namesapce里面就行了吧？

**Comment by zplzpl** [comment]
@philchia http://106.12.25.204:8080/configs/spring-boot-dubbo-provider/default/test-yml
我在这个官方测试环境，测试了一下，发现通过HTTP接口拉取不到。报这个错误；

但配置内容很简单：

`name: Tom Smith`

**Comment by zplzpl** [comment]
我看到“properties”格式，有人这么做：

`test:[{"a": 1, "b", 2}]`

**Comment by philchia** [comment]
这样都是可以的

**Comment by zplzpl** [comment]
poller.go watchUpdates() 感觉还是需要有暴漏pumpUpdates错误的出口

**Comment by zplzpl** [comment]
感觉有返回error的地方，但是没处理error；not good，my friend.

**Comment by philchia** [comment]
嗯，后面考虑加上，也欢迎pr

**Comment by zplzpl** [comment]
CircleCI 这个好用？你们公司是用这个的？

**Comment by philchia** [comment]
这个属于个人项目，之前用travis，后面太慢了，换了

**Comment by zplzpl** [comment]
你的.gitignore很工整，是有什么生产工具帮助设置这些吗？

**Comment by philchia** [comment]
https://www.gitignore.io/

**Comment by zplzpl** [comment]
通过 app.properties 载入一些应用的配置，这个做法，后续你会改动吗？

**Comment by philchia** [comment]
这个并不是强制的

**Comment by zplzpl** [comment]
我划分了一下参数

app:
appId
clusterName
namespaceNames 

apollo:
config_server_url

我觉得apollo这部分的变量应该提取出来，这样做持续交付的时候，配置改一份，直接推送给所有不同的appid，如果放在一份，可能需要逐个appid改，然后我觉得const.go里面有些也可以放出来到apollo这里。

我个人理解……

**Comment by zplzpl** [comment]
或者说，除了 app.properties 这个方式还有没有，其它更好的方式去传递这些参数，考虑上容器与微服务
