### ISSUE TITLE
 The system cannot find the file specified

### ISSUE THREAD

**Issue by larkwins** [philchia/agollo#16]
app.properties:
```
{
    "appId": "test9910",
    "cluster": "default",
    "namespaceNames": ["application"],
    "ip": "xxx:8080"
}
```
agollo.Start() 
err:
```
open .test9910_default: The system cannot find the file specified.
```

But http api is OK!
![image](https://user-images.githubusercontent.com/3422759/53072475-29525d00-3520-11e9-866e-dc292dd0883e.png)

Why?

**Comment by philchia** [comment]
this may because the request to http api failed and can not find local cache file

**Comment by weisd** [comment]
windows 10 ?

**Comment by wolking** [comment]
@philchia Has it been fixed?I had the same problem

**Comment by philchia** [comment]
> @philchia Has it been fixed?I had the same problem

pls provide your os name and your go version, thx

**Comment by wolking** [comment]
@philchia windows10,go version 1.12.5.
github.com/philchia/agollo v2.1.0+incompatible // indirect


> > @philchia Has it been fixed?I had the same problem
> 
> pls provide your os name and your go version, thx

windows10, go version 1.12.5.
github.com/philchia/agollo v2.1.0+incompatible // indirect
