### ISSUE TITLE
配置全部作为string类型，需要应用自己断言具体的类型

### ISSUE THREAD

**Issue by LHRchina** [philchia/agollo#17]
go 的client 通过GetStringValue() 这个函数获取某个key对应的配置，但获取的配置是没有类型的，都是作为string处理，这点是否和其他语言的客户端一致？如果一致，为何不区分类型？

**Comment by philchia** [comment]
agollo配置内部存储都是字符串，都是没有类型的，client只是把配置拿出来，需要其他类型的需要自己做转换并处理错误

**Comment by LHRchina** [comment]
> agollo配置内部存储都是字符串，都是没有类型的，client只是把配置拿出来，需要其他类型的需要自己做转换并处理错误

thx！还有一个问题：go client 是否和Java 的client 特性保持一致呢？如果在生产环境使用go client 是否可靠

**Comment by philchia** [comment]
跟java client无任何关系，我司已在生产环境使用了很长时间

**Comment by LHRchina** [comment]
> 跟java client无任何关系，我司已在生产环境使用了很长时间

非常感谢，希望有机会进一步交流学习
