### ISSUE TITLE
No error throws while ip configured a connectable but invalid server

### ISSUE THREAD

**Issue by Colstuwjx** [philchia/agollo#28]
Hi,

It seems that we don't handled the following case well:

```
# app.properties
{
    "appId":"eng-demo",
    "cluster":"default",
    "namespaceNames":["application"],
    "ip":"www.google.com"
}
```

agollo will hang with start, and no errors output.
Such case could be reproduced while our apollo meta service broken, and the tcp port is still connectable, but no valid results return.

Thanks.

**Comment by ermazi** [comment]
+1
