### ISSUE TITLE
为什么移除mapstructure?

### ISSUE THREAD

**Issue by zplzpl** [philchia/agollo#31]
是有什么缺点？

**Comment by philchia** [comment]
想了下不是太适合加在客户端中，你可以自己在client外封装一层，我还是希望client的代码保持简洁

**Comment by zplzpl** [comment]
我觉得不应该把这个项目看的这么纯粹啊，这种方便大家的东西，应该是成为client的一部分

**Comment by philchia** [comment]
你可以自己fork，目前使用gomodule已经支持fork分支
