### ISSUE TITLE
能否提供一个使用的例子

### ISSUE THREAD

**Issue by changjiasheng** [philchia/agollo#35]
`xxdeMacBook-Pro:ph-agollo-master xx$ go run agollo_test.go
go run: cannot run *_test.go files (agollo_test.go)`

我通过git clone 下载下来工程，通过上述命令跑了下测试，跑不起来。
希望能够提供一个样例，这样方便使用。

**Comment by philchia** [comment]
`go test ./...` 这样跑测试

**Comment by changjiasheng** [comment]
不好意思，我对GO不太熟，我按照您说的方式尝试了，报错如下：
`changjiashengdeMacBook-Pro:ph-agollo-master changjiasheng$ go test ./agollo_test.go 
# command-line-arguments
./agollo_test.go:34:12: undefined: Start
./agollo_test.go:38:12: undefined: StartWithConfFile
./agollo_test.go:42:12: undefined: StartWithConfFile
./agollo_test.go:45:8: undefined: Stop
./agollo_test.go:46:18: undefined: defaultClient
./agollo_test.go:48:12: undefined: defaultClient
./agollo_test.go:53:13: undefined: WatchUpdate
./agollo_test.go:60:9: undefined: GetStringValue
./agollo_test.go:65:10: undefined: GetAllKeys
./agollo_test.go:76:8: undefined: defaultClient
./agollo_test.go:76:8: too many errors
FAIL	command-line-arguments [build failed]
`
麻烦再指导下。

**Comment by philchia** [comment]
`$go test ./...`
这样的命令
