### ISSUE TITLE
有实现获取Apollo配置文本的接口吗？

### ISSUE THREAD

**Issue by sundayslove** [philchia/agollo#36]
有实现下面这个接口吗
URL: {config_server_url}/configfiles/{appId}/{clusterName}/{namespaceName}?ip={clientIp}

**Comment by philchia** [comment]
GetNameSpaceContent

**Comment by sundayslove** [comment]
> GetNameSpaceContent

这个好像只能获取非properties格式的配置文本，里面指定了"content"作为键值，底层实现的接口是：{config_server_url}/**configs**/{appId}/{clusterName}/{namespaceName}?releaseKey={releaseKey}&ip={clientIp}


找了一下，agollo似乎没实现Apollo直接获取文本的接口：
{config_server_url}/**configfiles**/{appId}/{clusterName}/{namespaceName}?ip={clientIp}

> [microservice@test1 ismp-mesher]$ curl localhost:8080/configfiles/SampleApp/default/application   
> name=test
> timeout=100
> [microservice@test1 ismp-mesher]$ curl localhost:8080/configfiles/json/SampleApp/default/application
> {"name":"test","timeout":"100"}

用这个接口的话刷配置到本地文件会比较方便，配置文件的格式也可以定制。

**Comment by philchia** [comment]
这个我后面看下吧，也欢迎pr
