### ISSUE TITLE
是不是可以丰富一下Apollo的这个文档啊，看着有点抽象，不知道杂用的

### ISSUE THREAD

**Issue by shubiao-yao** [philchia/agollo#40]
是不是可以丰富一下Apollo的这个文档啊，看着有点抽象，不知道杂用的

**Comment by shubiao-yao** [comment]
![image](https://user-images.githubusercontent.com/32409300/58153688-3d823380-7ca2-11e9-8325-3e09682b79c4.png)
给你提个bug @philchia

**Comment by shubiao-yao** [comment]
![image](https://user-images.githubusercontent.com/32409300/58153949-fcd6ea00-7ca2-11e9-97b7-997d33d9c3fd.png)
又发现一个 @philchia

**Comment by tcchend** [comment]
给个例子吧，不知道怎么用，谢谢
