### ISSUE TITLE
配置文件的本地缓存能手动指定吗？

### ISSUE THREAD

**Issue by lifei6671** [philchia/agollo#44]
Mac 上使用这个库，总是报错 `open .6e77bd897fe903ad_default: no such file or directory` 目测是创建这个文件出错，看代码是根据APPID和namespace 拼接的，实际应用中，可能程序运行的目录没有创建权限，能够公开方法指定保存目录呢？

还有一个就是，我们的Apollo 配置的是 https 访问，我看代码里面是写死的HTTP。

**Comment by philchia** [comment]
1.
	CacheDir       string   `json:"cacheDir,omitempty"`
配置里面有的
2. 这个我后续会改下

**Comment by lifei6671** [comment]
我用的`go mod tidy`拉取的代码，应该是没发最新版吧，拉取的还是之前的老代码，我手动去掉了版本号就可以了。

**Comment by philchia** [comment]
我看了下 v2.3.0是有的

**Comment by lifei6671** [comment]
是有，但是应该跟go的module包没配合起来，导致我直接用2.3.0的版本号拉不到包，版本好直接自动变成了`v0.0.0-20190604065617-149e9ad9dd55`. 
就算我强制使用命令`go mod edit -require="github.com/philchia/agollo@v2.3.0"` 设置为新版本，最后还是自动变回来。

没搞明白是咋回事。
