### ISSUE TITLE
go get github.com/philchia/agollo@v2.3.1 failed

### ISSUE THREAD

**Issue by weisd** [philchia/agollo#53]
go version 1.13.1

go: finding github.com/philchia/agollo v2.3.1
go: finding github.com/philchia/agollo v2.3.1
go get github.com/philchia/agollo@v2.3.1: github.com/philchia/agollo@v2.3.1: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

see : https://github.com/golang/go/wiki/Modules#semantic-import-versioning
should change the package name when major version greater than 1

**Comment by weisd** [comment]
#54

**Comment by myholiday** [comment]
@weisd I met the same problem. 
https://sum.golang.org/lookup/github.com/philchia/agollo@v2.3.1+incompatible
I change go version to 1.12.12, it used to be 1.13.1. 
it works

**Comment by philchia** [comment]
try export GOSUMDB=off

**Comment by philchia** [comment]
#54 closed
