### ISSUE TITLE
apollo服务端对客户端造成的影响

### ISSUE THREAD

**Issue by newlipeng** [philchia/agollo#55]
此问题由apollo服务端没有正确理解namespace=application/application.properties造成客户端的循环调用问题。

client := agollo.NewClient(&agollo.Conf{
        AppID:          "agollotest",
        Cluster:        "default",
        NameSpaceNames: []string{"application"},
        //NameSpaceNames: []string{"application.properties"},
        CacheDir:       "c:\\tmp",
        IP:             "10.255.242.227:8080",
    })
如果采用没有注释掉的配置，则
notifications/v2?appId=agollotest&cluster=default&notifications=接口
会正常等待 60 second，则agollo客户端是正常的

当采用注释掉的配置时“NameSpaceNames: []string{"application.properties"},”
notifications/v2?appId=agollotest&cluster=default&notifications=接口
会立刻返回，导致agollo客户端循环调用此接口，造成一定的性能损耗

**Comment by philchia** [comment]
后续考虑把application namespace作为默认的namespace
