### ISSUE TITLE
获取不到全量value数据

### ISSUE THREAD

**Issue by jjvsun** [philchia/agollo#58]
能不能提供一个获取.properties文件全量的key，value的json数据的方法

**Comment by philchia** [comment]
可以先用GetAllKeys

**Comment by jjvsun** [comment]
> 可以先用GetAllKeys

可是不能根据keys获取全量的value数据。

**Comment by philchia** [comment]
先遍历keys，单独去拿吧，后面考虑提供这个接口

**Comment by jjvsun** [comment]
> 先遍历keys，单独去拿吧，后面考虑提供这个接口

好吧
