### ISSUE TITLE
GetNameSpaceContent did NOT support .properties namespace

### ISSUE THREAD

**Issue by Colstuwjx** [philchia/agollo#60]
While I use `GetNameSpaceContent` get .properties namespace content by agollo, I would got empty string.

I have been filed [an issue](https://github.com/ctripcorp/apollo/issues/2847#issuecomment-567280506) to ctripcorp apollo repo, and confirmed that it was support by apollo itself.

Thanks.

**Comment by philchia** [comment]
try remove the .properties suffix in namespace name

**Comment by philchia** [comment]
try remove the .properties suffix in namespace name

**Comment by Colstuwjx** [comment]
User has been tried without `.properties` suffix, see [issue](https://github.com/bilibili/kratos/issues/456#issue-538308347), it still didn't work.

**Comment by philchia** [comment]
This is because the json api did not response the content key for properties namespace

**Comment by philchia** [comment]
The json api for fetch content of .properties namespace which return the parsed result as a key value map, therefore its not possible to get the raw content of the .properties from the content key.

**Comment by Colstuwjx** [comment]
How about json.Marshal it as content key return?

**Comment by philchia** [comment]
the .properties file may contains a content key

**Comment by philchia** [comment]
i will try to fix it in a more graceful way
