### ISSUE TITLE
自定义的namespace在获取值得时候获取不到值

### ISSUE THREAD

**Issue by nosixtools** [philchia/agollo#7]
默认的application是可以获取到配置的，新建的namespace里边的配置获取不到，

{
    "appId":"babel",
    "cluster":"DEV",
    "namespaceNames":["application","Test.babel"],
    "ip":"***"
}

**Comment by philchia** [comment]
获取非默认namespace的配置需要用GetStringValueWithNameSapce这个接口

**Comment by nosixtools** [comment]
感谢解答，问题已解决
