### ISSUE TITLE
v3.1.1版本访问https请求还是会报证书问题

### ISSUE THREAD

**Issue by panyaowei** [philchia/agollo#73]
代码中新增了关闭配置，但是debug下 在发送请求还是拿着http包下的client对象发送。

**Comment by panyaowei** [comment]
agolloClient.longPoller = newLongPoller(conf, longPollInterval, agolloClient.handleNamespaceUpdate) 
//
newLongPoller 这个方法里面给全局的http client对象又赋值了，覆盖掉了原来关闭https校验的设置。。。。。。。。。

**Comment by philchia** [comment]
使用 v3.1.2-beta看是否解决你的问题

**Comment by panyaowei** [comment]
美女 你啥时候发个新版本出来呀。我们公司要入库。

**Comment by philchia** [comment]
v3.1.2-beta 这个tag已经打了，你测试下有没有问题？没问题我就发一个正式版本

**Comment by philchia** [comment]
v3.1.2 released

**Comment by panyaowei** [comment]
好的 我下午测试下

**Comment by panyaowei** [comment]
master分支 https请求没问题， 就是 有个option.go 文件是干嘛的 里面有变量未定义

**Comment by philchia** [comment]
这个不是master分支的吧
