### ISSUE TITLE
日志一直连续打印

### ISSUE THREAD

**Issue by panyaowei** [philchia/agollo#76]
[agollo] 2020/07/14 19:56:50 [INFO] sync namespace application with remote config server
[agollo] 2020/07/14 19:56:52 [INFO] handle namespace application update
[agollo] 2020/07/14 19:56:52 [INFO] sync namespace application with remote config server

这三句日记一直无线打印。。。。
weChat pywvsai

**Comment by panyaowei** [comment]
不太明白为什么 非得加上application这个命名空间

**Comment by philchia** [comment]
你这个什么版本

**Comment by panyaowei** [comment]
> 你这个什么版本

v4呀。
