### ISSUE TITLE
没有考虑到默认集群更新的情况

### ISSUE THREAD

**Issue by panyaowei** [philchia/agollo#80]
监听自定义的集群名称下的命名空间，当default集群下同样名称的命名空间产生变化，会响应200，返回default集群修改的配置命名空间。  代码会调用/config请求去获取自定义集群下面的命名空间的配置变化，因为没有变化返回304。 

代码会无线循环此步骤。 /notification请求立即返回200，紧接着立即发起/config请求返回304。

意见：
  1、 当notification请求响应200， 立即更改内存里的notificationId值，然后在调用cofing请求
   2、同时起个定时任务，定时去拉取最新配置。以防更改通知值后，去掉用config请求失败，导致永远不会与配置中心的值一致

**Comment by philchia** [comment]
没太明白， /notification 这个请求，default集群更新了，为什么会返回

**Comment by panyaowei** [comment]
> 没太明白， /notification 这个请求，default集群更新了，为什么会返回

apollo服务端的机制呀， 他defalut集群更新，也会通知其他集群变化，你自己试下就发现啦。 因为当一个命名空间在你的集群找不到，他会去找default的

**Comment by philchia** [comment]
> > 没太明白， /notification 这个请求，default集群更新了，为什么会返回
> 
> apollo服务端的机制呀， 他defalut集群更新，也会通知其他集群变化，你自己试下就发现啦。 因为当一个命名空间在你的集群找不到，他会去找default的

我测试下看

**Comment by panyaowei** [comment]
> > > 没太明白， /notification 这个请求，default集群更新了，为什么会返回
> > 
> > 
> > apollo服务端的机制呀， 他defalut集群更新，也会通知其他集群变化，你自己试下就发现啦。 因为当一个命名空间在你的集群找不到，他会去找default的
> 
> 我测试下看

美女期待你的快速发布， 然后把默认添加application命名空间这段代码去掉

**Comment by philchia** [comment]
这里有个疑问，非默认集群是否需要先获取默认集群的配置，然后再用当前集群的配置做一次覆盖
