### ISSUE TITLE
apollo启动失败，请求的登陆页面，secret配置了

### ISSUE THREAD

**Issue by matthew188** [philchia/agollo#81]
这是我的代码，用的演示环境的地址：
`
演示环境（Demo）:
106.54.227.205
账号/密码:apollo/admin
`
`	// Some code here...

	agollo.Start(&agollo.Conf{
		AppID:              "my-test",
		Cluster:            "default",
		NameSpaceNames:     []string{"asfdasdfafadsf.properties"},
		CacheDir:           "/tmp",
		AccesskeySecret:    "589e4825d8c2431588d30488d7cbcee1",
		InsecureSkipVerify: true,
		MetaAddr:           "http://106.54.227.205" ,
	})

	//allKyes := agollo.GetAllKeys(agollo.WithNamespace("application"))
	val := agollo.GetString("redis")

	fmt.Println("allKyes:", val)`

报错是：
fail to preload open /tmp/.my-test_default: no such file or directory
调试的时候发现，请求的是singin页面去了，secret没有生效？

**Comment by matthew188** [comment]
求大佬解答 😊 。。

**Comment by matthew188** [comment]
![Uploading image.png…]()

**Comment by matthew188** [comment]
![image](https://user-images.githubusercontent.com/14805513/100434595-af2d1000-30d7-11eb-9823-06b702540e7d.png)
![image](https://user-images.githubusercontent.com/14805513/100434683-d388ec80-30d7-11eb-95df-a0a3fbcb0993.png)

**Comment by philchia** [comment]
MetaAddr 这个是meta的地址，你是不是配置成portal的了

**Comment by matthew188** [comment]
> MetaAddr 这个是meta的地址，你是不是配置成portal的了

是啊，发现是metaaddr的问题
