### ISSUE TITLE
Compatible with go modules

### ISSUE THREAD

**Issue by wweir** [philchia/agollo#9]
**Pre-knowledge**
Golang adds modules support in version 1.11. It has a semi version calculator in the golang compiler (go binary).
You can find the calculator implementation code via these links:
- https://github.com/golang/go/blob/release-branch.go1.11/src/cmd/go/internal/semver/semver.go#L115
- https://github.com/golang/go/blob/release-branch.go1.11/src/cmd/go/internal/semver/semver.go#L150

The trouble maker is:
<img width="381" alt="semiver-parser" src="https://user-images.githubusercontent.com/2841254/50418554-f31d9780-0866-11e9-9d65-1d43b3b76bc8.png">

**Real Problem**
While use `agollo` in a project with go modules, `go mod tidy` will use `master` as the default version but not latest stable version `2.1.0`.

**Suggestion**
Release a new version with a tag starting with "v", eg: v2.1.0.

**For Now** 
We can manually lock `agollo` by running `go get github.com/philchia/agollo 2.1.0` in project(go.mod) dirctory.

**Comment by philchia** [comment]
tag added, check if that works

**Comment by wweir** [comment]
LGTM.
```
require github.com/philchia/agollo v2.1.0+incompatible
```
